### ISSUE TITLE
Nové dokumenty k projektu

### ISSUE THREAD

**Issue by tauchmanovaM** [SemStew/SemStew#2]
**Nová dokumentace - něco jako cílový koncept**
Je potřeba vytvořit dokument, ve kterém vysvětlíme, proč projekt překlápíme do jiné technologie. V ní je třeba vysvětlit její aktuální stav, očekávaný stav, jaké klady a zápory to přinese a jak toho chceme dosáhnout. 

**Nová instalační příručka**
Je nutné vytvořit pro novou technologii novou instalační příručku s obsahem:
- Postup pro instalaci balíčku
- Vyžadované závislosti
- FAQ - seznam problémů a jejich řešení, které se mohou objevit při instalaci balíčku

**DEADLINE:** není přesně určen - ideálně do 1. iterace (přelom říjen/listopad)

**Comment by tauchmanovaM** [comment]
Na dokumentaci bychom mohli dělat všichni společně si myslím, respektive je potřeba spolupracovat. Času je málo a nás taky. Ideálně bych vytvořila dokument, něco jako cílový koncept a postupovat dle něj.

**Comment by smolidav** [comment]
Určitě to možné je a to, co jsi popsala, ty důvody a tak, tak mám o tom celkem jasnou představu :smiley: takže bych to probral na příštím sezení nebo tak a sepsali bychom to :wink:

**Comment by tauchmanovaM** [comment]
Cílový koncept je hotov. :)
